import type { DataRoomCard, DiligenceCategory } from '../types.js';

/**
 * Data Room cards (GDD §3.1, §7.1).
 *
 * Severity drives price impact; `repCategory` is the link that makes Phase 5
 * legal work pay off in Phase 7 — an undiscovered finding only becomes a
 * recoverable indemnity claim if the matching representation was negotiated
 * broadly enough to cover it.
 */
export const DATA_ROOM_CARDS: DataRoomCard[] = [
  // --- Financial -----------------------------------------------------------
  {
    id: 'dr-fin-clean-1',
    category: 'financial',
    severity: 'green',
    title: 'Clean Audit History',
    body: 'Three years of unqualified audit opinions from a national firm. No restatements, no material weaknesses in internal control.',
    priceImpactPct: [0, 0],
    flavor: 'The dog that did not bark. Worth noting precisely because it is unremarkable.',
  },
  {
    id: 'dr-fin-clean-2',
    category: 'financial',
    severity: 'green',
    title: 'Quality of Earnings Confirms Management Numbers',
    body: 'Independent QofE ties out to management’s adjusted EBITDA within 1.5%. Add-backs are documented and defensible.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-fin-addbacks',
    category: 'financial',
    severity: 'yellow',
    title: 'Aggressive EBITDA Add-Backs',
    body: 'Management’s adjusted EBITDA includes $18M of "one-time" costs that have recurred in each of the last three years. Normalised EBITDA is roughly 6% lower than presented.',
    priceImpactPct: [4, 7],
    remedy: 'Reprice off normalised EBITDA, or hold back the delta in escrow.',
    repCategory: 'financialStatements',
    latentIntegrationPct: 4,
    flavor: 'Every add-back is one-time until you see it three years running.',
  },
  {
    id: 'dr-fin-workingcapital',
    category: 'financial',
    severity: 'yellow',
    title: 'Working Capital Has Been Managed Down',
    body: 'Payables stretched from 42 to 68 days over the last two quarters. Roughly $30M of the reported cash balance is borrowed from suppliers and will normalise post-closing.',
    priceImpactPct: [3, 6],
    remedy: 'Set the working capital peg off a trailing twelve-month average, not the closing snapshot.',
    repCategory: 'financialStatements',
    latentIntegrationPct: 3,
  },
  {
    id: 'dr-fin-revrec',
    category: 'financial',
    severity: 'red',
    title: 'Revenue Recognition Timing',
    body: 'Multi-year contracts are being recognised substantially at signing rather than ratably. A restatement under a stricter reading would move roughly $95M of revenue into future periods.',
    priceImpactPct: [11, 18],
    remedy: 'Specific indemnity for restatement exposure plus an uncapped financial statements rep.',
    repCategory: 'financialStatements',
    latentIntegrationPct: 12,
    flavor: 'Not fraud. Not conservative either. The auditors signed it; the SEC might not.',
  },
  {
    id: 'dr-fin-fraud',
    category: 'financial',
    severity: 'black',
    title: 'Fabricated Revenue',
    body: 'The CFO has been booking revenue against a channel partner that has no corresponding purchase orders. Actual EBITDA is approximately 58% of reported. The audit committee does not know.',
    priceImpactPct: [35, 50],
    remedy: 'There is no remedy that makes this deal the deal you thought you were doing.',
    repCategory: 'financialStatements',
    latentIntegrationPct: 40,
    flavor: 'The reason you read the bank statements yourself.',
  },

  // --- Legal ---------------------------------------------------------------
  {
    id: 'dr-legal-clean-1',
    category: 'legal',
    severity: 'green',
    title: 'Corporate Records in Order',
    body: 'Minute books complete, cap table reconciled, all stock issuances properly authorised. No gaps in the corporate history.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-legal-clean-2',
    category: 'legal',
    severity: 'green',
    title: 'Litigation Docket Is Routine',
    body: 'Four open matters, all ordinary-course commercial disputes, aggregate exposure under $3M and fully reserved.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-legal-employment',
    category: 'legal',
    severity: 'yellow',
    title: 'Pending Employment Litigation',
    body: 'Former regional director alleging wrongful termination and retaliation. Counsel assesses $2–4M exposure with moderate probability of an adverse outcome.',
    priceImpactPct: [2, 4],
    remedy: 'Specific indemnity, dollar-for-dollar, outside the basket.',
    repCategory: 'litigation',
    latentIntegrationPct: 2,
  },
  {
    id: 'dr-legal-classaction',
    category: 'legal',
    severity: 'red',
    title: 'Consumer Class Action Certified',
    body: 'A class was certified last quarter covering eight years of billing practices. Plaintiffs’ damages model claims $180M; the company has reserved $12M.',
    priceImpactPct: [10, 16],
    remedy: 'Escrow sized to the reserve gap, or an uncapped specific indemnity with a long tail.',
    repCategory: 'litigation',
    latentIntegrationPct: 14,
    flavor: 'Certification is the moment the settlement value stops being theoretical.',
  },
  {
    id: 'dr-legal-quitam',
    category: 'legal',
    severity: 'red',
    title: 'Sealed Qui Tam Action',
    body: 'A relator complaint alleging off-label promotion has been under seal for 14 months. The government has not yet decided whether to intervene. Exposure $50–120M with treble damages available.',
    priceImpactPct: [9, 15],
    remedy: 'Specific indemnity surviving until the matter is finally resolved, backed by escrow.',
    repCategory: 'compliance',
    latentIntegrationPct: 13,
  },
  {
    id: 'dr-legal-fcpa',
    category: 'legal',
    severity: 'black',
    title: 'FCPA Exposure in Two Jurisdictions',
    body: 'Third-party distributors in two markets have been making payments to procurement officials at state-owned customers. The conduct is documented in internal audit files that were never escalated. Successor liability attaches.',
    priceImpactPct: [28, 45],
    remedy: 'Voluntary disclosure before signing, or walk. Successor liability follows the assets either way.',
    repCategory: 'compliance',
    latentIntegrationPct: 32,
  },

  // --- Operational ---------------------------------------------------------
  {
    id: 'dr-ops-clean-1',
    category: 'operational',
    severity: 'green',
    title: 'Facilities Well Maintained',
    body: 'Deferred maintenance is minimal, capex has tracked depreciation, and all facilities are operating below capacity with room to absorb growth.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-ops-clean-2',
    category: 'operational',
    severity: 'green',
    title: 'Supply Chain Is Dual-Sourced',
    body: 'Every critical input has at least two qualified suppliers. No single-source dependencies in the bill of materials.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-ops-singlesource',
    category: 'operational',
    severity: 'yellow',
    title: 'Single-Source Component Supplier',
    body: 'A sole supplier provides a component in 60% of units. The supply agreement expires in 11 months and contains no renewal obligation.',
    priceImpactPct: [3, 6],
    remedy: 'Condition closing on a renewed supply agreement, or price in the qualification cost of a second source.',
    repCategory: 'materialContracts',
    latentIntegrationPct: 4,
  },
  {
    id: 'dr-ops-deferredcapex',
    category: 'operational',
    severity: 'yellow',
    title: 'Deferred Capital Expenditure',
    body: 'Capex has run at 40% of depreciation for three years. Catch-up investment of roughly $45M is needed within 24 months to maintain current output.',
    priceImpactPct: [4, 7],
    remedy: 'Reduce price by the present value of the catch-up spend.',
    latentIntegrationPct: 5,
    flavor: 'Margins look excellent right up until the machines need replacing.',
  },
  {
    id: 'dr-ops-cyber',
    category: 'operational',
    severity: 'red',
    title: 'Undisclosed Security Incident',
    body: 'An intrusion 14 months ago exfiltrated customer records. The company concluded no notification obligation was triggered. Outside counsel’s memo reaching that conclusion is thin, and three states’ statutes say otherwise.',
    priceImpactPct: [8, 14],
    remedy: 'Specific indemnity covering notification, regulatory penalties and consumer claims.',
    repCategory: 'compliance',
    latentIntegrationPct: 12,
  },

  // --- Commercial ----------------------------------------------------------
  {
    id: 'dr-comm-clean-1',
    category: 'commercial',
    severity: 'green',
    title: 'Diversified Customer Base',
    body: 'No customer exceeds 6% of revenue. Net revenue retention has run above 108% for three years.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-comm-clean-2',
    category: 'commercial',
    severity: 'green',
    title: 'Backlog Confirms Guidance',
    body: 'Contracted backlog covers 82% of next year’s revenue plan. Cancellation rights are limited and rarely exercised.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-comm-concentration',
    category: 'commercial',
    severity: 'yellow',
    title: 'Customer Concentration',
    body: 'The top three customers represent 61% of revenue. All three are on twelve-month auto-renewal terms with 30-day termination for convenience.',
    priceImpactPct: [5, 8],
    remedy: 'Earn-out tied to retention of the top three, or a holdback released on renewal.',
    repCategory: 'materialContracts',
    latentIntegrationPct: 6,
    flavor: 'Termination for convenience is doing an enormous amount of work in that sentence.',
  },
  {
    id: 'dr-comm-changeofcontrol',
    category: 'commercial',
    severity: 'red',
    title: 'Change-of-Control Termination Right',
    body: 'The largest distribution agreement — 30% of revenue — gives the counterparty a termination right on a change of control. No consent has been sought, and the counterparty competes with the buyer in two markets.',
    priceImpactPct: [12, 22],
    remedy: 'Make the consent a closing condition, or accept that you may be buying a business without its largest channel.',
    repCategory: 'materialContracts',
    latentIntegrationPct: 18,
  },
  {
    id: 'dr-comm-pricing',
    category: 'commercial',
    severity: 'yellow',
    title: 'Below-Market Pricing Locked In',
    body: 'The two largest contracts were repriced downward last year to win renewal. Both run four more years with no escalator. Roughly 180bps of margin is contractually unavailable.',
    priceImpactPct: [3, 6],
    repCategory: 'materialContracts',
    latentIntegrationPct: 4,
  },

  // --- HR / Labor ----------------------------------------------------------
  {
    id: 'dr-hr-clean-1',
    category: 'hr',
    severity: 'green',
    title: 'Stable Workforce',
    body: 'Voluntary attrition at 9%, below sector norms. No union activity, no open NLRB matters, benefit plans fully funded.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-hr-clean-2',
    category: 'hr',
    severity: 'green',
    title: 'Management Committed',
    body: 'All eight executive officers have signed retention agreements running 24 months past a change of control.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-hr-parachutes',
    category: 'hr',
    severity: 'yellow',
    title: 'Golden Parachutes Trigger on Closing',
    body: 'Change-of-control payments to eleven executives total $62M, with excise tax gross-ups on four of them. Single-trigger, not double.',
    priceImpactPct: [3, 5],
    remedy: 'Price it in — this is a cash cost at closing, not a contingency.',
    repCategory: 'employees',
    latentIntegrationPct: 3,
  },
  {
    id: 'dr-hr-keyman',
    category: 'hr',
    severity: 'red',
    title: 'Key Engineering Team Is a Flight Risk',
    body: 'The eleven engineers who built the core platform have no retention agreements, and two have been approached by a competitor. Institutional knowledge is undocumented.',
    priceImpactPct: [8, 13],
    remedy: 'Condition closing on signed retention packages for the named individuals.',
    repCategory: 'employees',
    latentIntegrationPct: 15,
  },
  {
    id: 'dr-hr-misclass',
    category: 'hr',
    severity: 'yellow',
    title: 'Worker Misclassification',
    body: 'Roughly 900 field workers are engaged as independent contractors under a test that two states have recently narrowed. Back-tax and benefits exposure of $20–35M.',
    priceImpactPct: [4, 7],
    remedy: 'Specific indemnity through the statute of limitations.',
    repCategory: 'compliance',
    latentIntegrationPct: 6,
  },

  // --- Tax -----------------------------------------------------------------
  {
    id: 'dr-tax-clean-1',
    category: 'tax',
    severity: 'green',
    title: 'Returns Filed, No Open Audits',
    body: 'All federal, state and foreign returns filed on time. No examinations open. Reserves for uncertain positions look conservative.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-tax-clean-2',
    category: 'tax',
    severity: 'green',
    title: 'NOLs Available and Usable',
    body: '$140M of federal NOLs with no prior ownership change. Section 382 limitation will apply post-closing but the carryforward retains substantial value.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-tax-transferpricing',
    category: 'tax',
    severity: 'yellow',
    title: 'Transfer Pricing Position Is Aggressive',
    body: 'IP was migrated to a low-tax jurisdiction four years ago on a valuation that the company’s own advisers described as "at the edge of defensible". Exposure $25–60M across two authorities.',
    priceImpactPct: [3, 6],
    remedy: 'Specific tax indemnity surviving to the end of the assessment period.',
    repCategory: 'tax',
    latentIntegrationPct: 5,
  },
  {
    id: 'dr-tax-audit',
    category: 'tax',
    severity: 'red',
    title: 'IRS Examination With Proposed Adjustment',
    body: 'An examination of the last three years has produced a notice of proposed adjustment of $85M plus penalties. The company is contesting; counsel puts success at roughly even odds.',
    priceImpactPct: [7, 12],
    remedy: 'Escrow the full proposed adjustment, released on final resolution.',
    repCategory: 'tax',
    latentIntegrationPct: 10,
  },

  // --- Environmental -------------------------------------------------------
  {
    id: 'dr-env-clean-1',
    category: 'environmental',
    severity: 'green',
    title: 'Phase I Assessments Clean',
    body: 'Phase I ESAs completed at all owned sites within the last 18 months. No recognised environmental conditions identified.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-env-clean-2',
    category: 'environmental',
    severity: 'green',
    title: 'Permits Current and Transferable',
    body: 'All operating permits are current, and each is transferable on a change of control without agency consent.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-env-contamination',
    category: 'environmental',
    severity: 'red',
    title: 'Legacy Contamination',
    body: 'Phase II assessment reveals significant soil and groundwater contamination at the primary manufacturing facility. Estimated remediation $30–75M. The state agency is aware but has issued no formal order. Environmental policies lapsed three years ago.',
    priceImpactPct: [8, 15],
    remedy: 'Uncapped environmental indemnity, or a 20% escrow held for ten years.',
    repCategory: 'environmental',
    latentIntegrationPct: 15,
    flavor: 'The sampling report is in the data room. It is filed under "Facilities — Miscellaneous".',
  },
  {
    id: 'dr-env-emissions',
    category: 'environmental',
    severity: 'yellow',
    title: 'Emissions Compliance Gap',
    body: 'Two facilities exceed permitted emission limits during peak production. Self-reported once; not since. Capital fix costs $18M.',
    priceImpactPct: [2, 5],
    remedy: 'Price in the capital fix and take a compliance rep without a materiality qualifier.',
    repCategory: 'environmental',
    latentIntegrationPct: 4,
  },

  // --- IP / Technology -----------------------------------------------------
  {
    id: 'dr-ip-clean-1',
    category: 'ip',
    severity: 'green',
    title: 'IP Ownership Documented',
    body: 'All invention assignments executed, all registrations current, chain of title clean on every material patent family.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-ip-clean-2',
    category: 'ip',
    severity: 'green',
    title: 'Open Source Use Is Compliant',
    body: 'Automated scanning shows no copyleft licences in distributed code. Attribution obligations are satisfied.',
    priceImpactPct: [0, 0],
  },
  {
    id: 'dr-ip-patentchallenge',
    category: 'ip',
    severity: 'red',
    title: 'Patent Challenge on the Lead Product',
    body: 'A generic manufacturer has filed an IPR petition against the patent covering 44% of revenue. Institution decision is due in five months. An adverse outcome pulls the exclusivity cliff forward by two years.',
    priceImpactPct: [12, 20],
    remedy: 'CVR tied to the outcome, or a price cut sized to the probability-weighted loss.',
    repCategory: 'ip',
    latentIntegrationPct: 17,
  },
  {
    id: 'dr-ip-noncompete',
    category: 'ip',
    severity: 'yellow',
    title: 'Founder Non-Compete Dispute',
    body: 'Two senior scientists joined from a competitor that is asserting trade secret misappropriation. No adjudication yet, but the complaint identifies technology in the current product.',
    priceImpactPct: [3, 6],
    remedy: 'Specific IP indemnity plus a rep that no third-party IP is required to run the business.',
    repCategory: 'ip',
    latentIntegrationPct: 5,
  },
  {
    id: 'dr-ip-license',
    category: 'ip',
    severity: 'yellow',
    title: 'Inbound Licence Is Not Assignable',
    body: 'A licence covering technology embedded in the flagship product prohibits assignment and is silent on change of control. The licensor is a competitor.',
    priceImpactPct: [4, 8],
    remedy: 'Obtain consent pre-closing, or structure to avoid triggering assignment.',
    repCategory: 'ip',
    latentIntegrationPct: 7,
  },
  {
    id: 'dr-ip-opensource',
    category: 'ip',
    severity: 'red',
    title: 'Copyleft Contamination',
    body: 'GPL-licensed code is compiled into the distributed binary of the core product. A strict reading obliges the company to release its own source. No remediation has been attempted.',
    priceImpactPct: [9, 16],
    remedy: 'Condition closing on a clean-room rewrite, or take an uncapped IP indemnity.',
    repCategory: 'ip',
    latentIntegrationPct: 13,
  },
];

export const DATA_ROOM_BY_ID: Record<string, DataRoomCard> = Object.fromEntries(
  DATA_ROOM_CARDS.map((c) => [c.id, c]),
);

/** Clean filler cards, used to pad a category once its seeded findings are placed. */
export const CLEAN_CARDS_BY_CATEGORY: Record<DiligenceCategory, DataRoomCard[]> =
  DATA_ROOM_CARDS.reduce(
    (acc, card) => {
      if (card.severity === 'green') acc[card.category].push(card);
      return acc;
    },
    {
      financial: [],
      legal: [],
      operational: [],
      commercial: [],
      hr: [],
      tax: [],
      environmental: [],
      ip: [],
    } as Record<DiligenceCategory, DataRoomCard[]>,
  );

/** Non-clean findings, used to seed a target's hidden risks. */
export const RISK_CARDS: DataRoomCard[] = DATA_ROOM_CARDS.filter((c) => c.severity !== 'green');
